figgy/cart/urls.py
from django.urls import path
from . import views


app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

figgy/credentials/urls.py
from . import views
from django.urls import path


app_name='credentials'
urlpatterns = [

    path('register', views.register, name='register'),
    path('login',views.login,name='login'),
    path('logout', views.logout, name='logout'),



]

figgy/figgy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('figgyapp.urls')),
    path('credentials/',include('credentials.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                         document_root= settings.MEDIA_ROOT)

figgy/figgyapp/urls.py
from django.urls import path
from . import views
app_name='figgyapp'

urlpatterns =[

    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail'),
    path('order',views.order,name='order'),
    path('foodorder',views.foodorder,name='foodorder'),
]

figgy/search_app/urls.py
from django.urls import path
from . import views


app_name='search_app'
urlpatterns = [

    path('',views.SearchResult,name='SearchResult'),
]

figgy/cart/models.py
from django.db import models
from figgyapp.models import Product


class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

figgy/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from figgyapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
                cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

figgy/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static 'css/custom.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Roboto+Slab:wght@600&family=Roboto:wght@100&display=swap" rel="stylesheet">
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>


<div class="container">


{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</div>

</body>
</html>

figgy/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is the cart page. proceed to review your items and place the order
{% endblock %}
{% block title %}
    Cart -Figgy Erestaurant Pvt Ltd.
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'figgyapp:allProdCat' %}">Here</a>to continue shopping.
        </p>
<br>
<br>
        <br>
        <br>
        <br>
        <br>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>

    </div>
<div class="row mx-auto">
    <div class="col-sm-12 col-sm-12 col-sm-12 col-sm-12 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>

            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>

                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: $ {{cart_item.product.price}}
                    <br>
                    Qty : {{cart_item.quantity}} X $ {{cart_item}}

                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product %}
                <td>
                    <a href="{% url  'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                     &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>

                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-sm-12 col-sm-12 col-sm-12 col-sm-12 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
                Checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                Please review your shopping cart items before proceeding with the order payment.
            </td>
        </tr>
        <tr>
            <td class="text-left">
                Your Total is: <strong> {{ total }} </strong>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'figgyapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a> <a href="{% url 'figgyapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Order Food</a>



    </div>

</div>
    {% endif %}
</div>
</div>
</div>



{% endblock %}>

figgy/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
         {{ category.description|truncatewords:155 }}
    {% else %}
         Welcome to Figgy....We serve you quality Foods....
    {% endif %}
{% endblock %}
{% block title %}
{% if category %}
         {{ category.name}}- Figgy Store
    {% else %}
         See what's todays special......
    {% endif %}
{% endblock %}

{% block content %}
<style>
.container {
  position: relative;
  width: 50%;
}
.container img {
  width: 50%;
  height: auto;
  position: relative;
  left: -60%;
  right:100%;
}
.container .btn {
  position: absolute;
  top: 80%;
  left: 55%;
  transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  background-color: #555;
  color: white;
  font-size: 16px;
  padding: 12px 24px;
  border: none;
  cursor: pointer;
  border-radius: 5px;
}

.container .btn:hover {
  background-color: black;
}
</style>
<!--{% if category %}-->

<!--   <div>-->
<!--       <div class="row my_row_class">-->
<!--           <div class="mx-auto">-->
<!--           <p><a href="{% url 'figgyapp:allProdCat' %}"> Our Special Items</a></p>-->
<!--       </div>-->
<!--           </div>-->
<!--   </div>-->
<!--   {% endif %}-->
<!--<div class="mx-auto">-->
<!--    {% if category %}-->
<!--    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">-->
<!--</div>-->
<!--   <br>-->
<!--<div>-->
<!--    <h1 class="text-center my_title">{{category.name}}</h1>-->
<!--    <p class="text-justify">{{category.description}}</p>-->
<!--</div>-->
<!--    {% else %}-->
<div class="container">
   <img src="{% static 'img/freshfood.jpg' %}" alt="our products" style="width:700px;height:500px;">
   <button class="btn"><b><a href="credentials/login">FOR BOOKING</b></a></button>
</div>

<!--<div>-->
<!--    <h1 class="text-center my_title"><b>Our Items</b></h1>-->
<!--    <p class="text-center">We serve good and quality foods which fullfill your hungry and mind.</p>-->
<!--</div>-->
<!--   {% endif %}-->
<!--<div class="container">-->
<!--    <div class="row mx-auto">-->
<!--        {% for product in products.object_list %}-->
<!--        <div class="my_bottom_margin col-9 col-sm-4 col-sm-4 xol-lg-4">-->
<!--            <div class="card text-center" style="min-width:18rem;">-->
<!--                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>-->
<!--                <div class="card-body">-->
<!--                    <h4>{{product.name}}</h4>-->
<!--                    <p>{{product.price}}</p>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--</div>-->
<!--    <div class=" row mx-auto">-->
<!--        {% if products.paginator.num_pages > 1 %}-->

<!--        <hr>-->
<!--        <br>-->
<!--        <br>-->
<!--        <br>-->
<!--        <div class="text-center">-->
<!--            {% for pg in products.paginator.page_range %}-->
<!--                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>-->
<!--            {% endfor %}-->

<!--        </div>-->
<!--        {% endif %}-->
    </div>
</div>
{% endblock %}

figgy/templates/foodorder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>foodorder</title>
</head>
<body>
<h1>Food Ordering Form</h1>
<style>
body {background-color: powderblue;}
h1 {
  color: blue;
  font-family: times new roman;
  font-size: 300%;
  text-align: center;
}
</style>
<form style="margin: auto; width: 170px;" class="row g-3 needs-validation" novalidate>
  <div class="col-md-4">
    <label for="validationCustom01" class="form-label">Customer name</label>
    <input type="text" class="form-control" id="validationCustom01"  required>
  </div>
  <div class="col-md-4">
    <label for="validationCustom02" class="form-label">Phone number</label>
    <input type="text" class="form-control" id="validationCustom02"  required>
    <div class="valid-feedback">
    </div>
  </div>
  <div class="col-md-4">
    <label for="validationCustomUsername" class="form-label">Address</label>
    <div class="input-group has-validation">
      <input type="text" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required>
    </div>
  </div>
    <br>
  <select id="district" onchange="ChangedistrictList()">
  <option value="">-- district --</option>
  <option value="Al">Alappuzha</option>
  <option value="Er">Ernakulam</option>
  <option value="Kl">Kollam</option>
  <option value="Kt">Kottayam</option>
  <option value="Th">Thrissur</option>
  <option value="Pa">Palakkad</option>
  <option value="Tr">Trivandrum</option>
</select>

<select id="town"></select>
    <br>

<script>
var districtsAndtowns = {};
districtsAndtowns['Al'] = ['Cherthala', 'Ambalappuzha', 'Kuttanad'];
districtsAndtowns['Er'] = ['Kochi', 'Palarivattom', 'kumbalangi', 'Kakkanad'];
districtsAndtowns['Kl'] = ['Vaadi', 'Chathannor', 'Parippally'];
districtsAndtowns['Kt'] = ['Thiruvalla', 'Changanassery', 'Erattupaetta'];
districtsAndtowns['Th'] = ['chalakkudii', 'iringalakkuda', 'guruvayur'];
districtsAndtowns['Pa'] = ['chandranagar', 'ottappalam', 'Pattambi'];
districtsAndtowns['Tr'] = ['Varkala', 'kazhakkotam', 'chakka'];


function ChangedistrictList() {
    var districtList = document.getElementById("district");
    var townList = document.getElementById("town");
    var seldistrict = districtList.options[districtList.selectedIndex].value;
    while (townList.options.length) {
        townList.remove(0);
    }
    var districts = districtsAndtowns[seldistrict];
    if (districts) {
        var i;
        for (i = 0; i < districts.length; i++) {
            var district = new Option(districts[i], i);
            townList.options.add(district);
        }
    }
}
</script>

  <div class="col-md-3">
    <label for="validationCustom05" class="form-label">Email</label>
    <input type="email" class="form-control" id="validationCustom05" required>
  </div>
  <br>
  <br>
   <div class="col-md-6">
    <label for="validationCustom06" class="form-label">Food</label>
    <select class="form-select" id="validationCustom06" required>
       <option selected disabled value="">Choose...</option>
        <option>Burger $25</option>
        <option>sandwitch $30</option>
        <option>limejuice $15</option>
        <option>cone icecream $15</option>
        <option>chicken biriyani $125</option>
        <option>shawarma $55</option>
        <option>shawayi $500</option>
        <option>chicken Mandhi $700</option>
        <option>orange juice $25</option>
        <option>vanilla sharja $55</option>
    </select>
      <br>
      <br>
  </div>
     <div class="col-md-5">
    <label for="validationCustom06" class="form-label">Quantity</label>
    <select class="form-select" id="validationCustom07" required>
       <option selected disabled value="">Choose...</option>
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
    </select>
      <br>
      <br>
  </div>
  <div class="col-12">
    <button onclick="alert('Your order is placed. Delivered within 20 minutes')">Submit</button>
  </div>
  <br>
   <div class="col-12">
    <button class="btn btn-primary" type="submit"><a href="{% url 'credentials:logout' %}">logout</a></button>
  </div>
</form>

</body>
</html>
<!--  <div class="col-md-6">-->
<!--    <label for="validationCustom03" class="form-label">District</label>-->
<!--    <select class="form-select" id="validationCustom03" required>-->
<!--       <option selected disabled value="">Choose...</option>-->
<!--        <option>Alappuzha</option>-->
<!--        <option>Ernakulam</option>-->
<!--        <option>Kollam</option>-->
<!--        <option>Trivandrum</option>-->
<!--        <option>Kottayam</option>-->
<!--        <option>Thrissur</option>-->
<!--        <option>Palakkad</option>-->
<!--    </select>-->

figgy/templates/footer.html
<div>
    <p class="text-center"><b>&copy; Figgy Erestaurant Pvt Ltd. All rights Reserved</b></p>
</div>

figgy/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'figgyapp:allProdCat' %}" <img src="{% static 'img/logo.png' %}" alt="logimage">
    </center>
</header>

figgy/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<h1>Login</h1>
<style>
body {background-color: powderblue;}
h1 {
  color: blue;
  font-family: times new roman;
  font-size: 300%;
  text-align: center;
}
</style>

<form style="margin: auto; width: 170px;" action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username" style="width: 200px;height: 30px;"><br>
    <input type="password" name="password" placeholder="enter your password"  style="width: 200px;height: 30px;"><br>
    <div>If you are a new user then click register
    <button type="button" class="btn btn-success"><a href="{% url 'credentials:register' %}">Register</a></button></div><br>
    <input type="submit">
    <div>If registration completed then click login
    <button type="button" class="btn btn-success"><a href="{% url 'figgyapp:order' %}">lOGIN</a></button></div><br>
</form>

</body>

</html>

figgy/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><b></b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<!--    <div>-->
<!--     <button type="button" class="btn btn-success"><a href="credentials/login">Booking</a></button>-->
<!--        </div>-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'figgyapp:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="credentials/login">Login</a>
        </li>
        <li class="nav-item">
           <a class="nav-link" href="credentials/register">Register</a>
        </li>
<!--        <li class="nav-item dropdown  {% if 'figgyapp' in request.path %} active {% endif %}">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            Shop-->
<!--          </a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--            <li><a class="dropdown-item" href="{% url 'figgyapp:allProdCat' %}">All Products</a></li>-->
<!--               {% for cat in links %}-->
<!--            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>-->
<!--               {% endfor %}-->

<!--          </ul>-->
<!--        </li>-->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Places
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Trivandrum</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">Kollam</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad">Palakkad</a></li>
            </li>
          </ul>
        </li>
<!--        {% if item_count > 0 %}-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>-->
<!--        </li>-->
<!--        {% endif %}-->
<!--      </ul>-->

<!--      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">-->
<!--        {% csrf_token %}-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>-->
<!--      </form>-->
    </div>
  </div>

</nav>
<!--<nav>-->
<!--    <ul>-->
<!--        <li><a href="{% url 'figgyapp:allProdCat' %}">All Products</a></li>-->
<!--        {% for cat in links %}-->

<!--        <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>-->
<!--        {% endfor %}-->
<!--        <li>Your Cart()</li>-->
<!--    </ul>-->
<!--</nav>-->

figgy/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<button onclick="displayDate()">The time is?</button>
</body>
</html>

figgy/templates/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>order</title>
</head>
<body>
<br>
<br>
<br>
<br>
<br>
<button style="width: 200px;height: 30px;" type="button" class="btn btn-primary"><a href="{% url 'figgyapp:foodorder' %}">food ordering</a></button>
<br>
<br>
</body>
</html>

figgy/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

         {{ product.description|truncatewords:155 }}



{% endblock %}
{% block title %}
{% if category %}
         {{ product.name}}- Figgy Store

    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'figgyapp:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="container"></div>
<br>
<br>

<div class="row">
    <div class="col-sm-12 col-sm-12 col-sm-12 col-sm-12 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>
    <div class="col-sm-12 col-sm-12 col-sm-12 col-sm-12">
        <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="text-center my_prod_text">{{product.description}}</p>
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
        </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}

figgy/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
<h2>Registration</h2>
<style>
body {background-color: pink;}
h2 {
  color: blue;
  font-family: times new roman;
  font-size: 300%;
  text-align: center;
}
</style>
<form style="margin: auto; width: 200px;" action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username" style="width: 200px;height: 30px;"><br>
    <input type="password" name="password" placeholder="enter your password" style="width: 200px;height: 30px;"><br>
    <input type="password" name="password1" placeholder="confirm  your password" style="width: 200px;height: 30px;"><br>
    <br>
    <button type="button" class="btn btn-success"><a href="{% url 'credentials:login' %}">Submit</a></button>


</form>
{% for msg in messages %}
{{msg}}
{% endfor %}

</body>
</html>

figgy/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        We have variety of products .
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b>{{query}}</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-4 col-sm-4 col-md-4 xol-lg-4">
            <div class="card" style="min-width:18rem;">
                <a href="{{product.get_url}}"> <img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
            <div class="card-body">
               <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
             </div>
             </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text"> 0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

figgy/templates/test.html
<select id="district" onchange="ChangedistrictList()">
  <option value="">-- district --</option>
  <option value="Al">Alappuzha</option>
  <option value="Er">Ernakulam</option>
  <option value="Kl">Kollam</option>
  <option value="Kt">Kottayam</option>
  <option value="Th">Thrissur</option>
  <option value="Pa">Palakkad</option>
  <option value="Tr">Trivandrum</option>
</select>

<select id="town"></select>

<script>
var districtsAndtowns = {};
districtsAndtowns['Al'] = ['Cherthala', 'Ambalappuzha', 'Kuttanad'];
districtsAndtowns['Er'] = ['Kochi', 'Palarivattom', 'kumbalangi'];
districtsAndtowns['Kl'] = ['Vaadi', 'Chathannor', 'Parippally'];
districtsAndtowns['Kt'] = ['Vaadi', 'Chathannor', 'Parippally'];
districtsAndtowns['Th'] = ['Vaadi', 'Chathannor', 'Parippally'];
districtsAndtowns['Pa'] = ['Vaadi', 'Chathannor', 'Parippally'];
districtsAndtowns['Tr'] = ['Vaadi', 'Chathannor', 'Parippally'];

function ChangedistrictList() {
    var districtList = document.getElementById("district");
    var townList = document.getElementById("town");
    var seldistrict = districtList.options[districtList.selectedIndex].value;
    while (townList.options.length) {
        townList.remove(0);
    }
    var districts = districtsAndtowns[seldistrict];
    if (districts) {
        var i;
        for (i = 0; i < districts.length; i++) {
            var district = new Option(districts[i], i);
            townList.options.add(district);
        }
    }
}
</script>

</body>
</html>